### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by mvrozanti** [jonahs99/c110#1]
Hello there! I've been very much interested in building a compiler for rule 110 and I found this repo. Sadly, I wasn't able to run it as expected. I'm not familiar with go so I figured I might be doing something wrong. I looked at the source code, specially under the elemulator directory but didn't find Matthew Cook's instructions.

**Comment by BioJonah** [comment]
I did not get very far with this. The go program is just a rule 110 emulator.

**Comment by mvrozanti** [comment]
Well, you're not alone. I've thought to myself, if I can understand Cook's instructions, I can build one myself. But I'm having the hardest time wrapping my head around this Cyclic Tag System thing. If you ever want to continue this project, hit me up.
